Import('env')

import os

include = env.Install('include', ['#include/nwutil.h'])
lib = env.Install('lib', ['../../src/libnwutil.a'])

if env["HOST_ARCH"] == env["ARCH"]:
    env.Alias(
        'install', env.Install(os.path.join(env['PREFIX'], 'include'), include),
    )
    env.Alias('install', env.Install(os.path.join(env['PREFIX'], 'lib'), lib))

env.FSEnvInstallLibConfig()
